package common.commands;

import common.interfaces.GameActionContext;
import java.io.Serial;

public class RequestCaseListCommand extends BaseCommand {
  @Serial private static final long serialVersionUID = 1L;

  public RequestCaseListCommand() {
    super(false);
  }

  @Override
  protected void executeCommandLogic(GameActionContext context) {
    // Server-side: GameSessionManager receives this command.
    // It prepares AvailableCasesDTO (containing all cases) and sends it back.
    // No specific logic needed here in the command itself, as it's just a request signal.
    // The actual response is generated by the GameSessionManager.
  }

  @Override
  public String getDescription() {
    return "Client request to the server for the list of available game cases.";
  }
}
